kind: ConfigMap
apiVersion: v1
metadata:
  namespace: clients
  name: java-cloud-producer-config
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.properties: |-
     bootstrap.servers=localhost:32400
     key.serializer=org.apache.kafka.common.serialization.StringSerializer
     value.serializer=org.apache.kafka.common.serialization.StringSerializer
     topic=chuck-java-topic
