kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: noproxy-clients
  name: namespace-reader
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-reader-binding
  namespace: noproxy-clients
subjects:
  - kind: ServiceAccount
    name: default
    apiGroup: ""
roleRef:
  kind: Role
  name: namespace-reader
  apiGroup: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: java-cloud-producer-noproxy
  name: java-cloud-producer-noproxy
  namespace: noproxy-clients
  annotations:
    configmap.reloader.stakater.com/reload: "java-cloud-producer-noproxy-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-cloud-producer-noproxy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-cloud-producer-noproxy
    spec:
      containers:
      - name: java-cloud-producer-noproxy
        image: ogomezso/java-cloud-producer:0.0.2
        resources: {}
        volumeMounts:
        - name: app-config-volume
          mountPath: /config
      volumes:
        - name: app-config-volume
          configMap:
            name: java-cloud-producer-noproxy-config
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: java-cloud-producer-noproxy
  name: java-cloud-producer-noproxy
  namespace: noproxy-clients
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: java-cloud-producer-noproxy
status:
  loadBalancer: {}
