kind: ConfigMap
apiVersion: v1
metadata:
  namespace: noproxy-clients
  name: java-cloud-producer-noproxy-config
  annotations:
    reloader.stakater.com/match: "true"
data:
  config.properties: |-
     bootstrap.servers=${CCLOUD_URL}
     ssl.endpoint.identification.algorithm=https
     security.protocol=SASL_SSL
     sasl.mechanism=PLAIN
     sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='${CCLOUD_APIKEY}' password=$'{CCLOUD_PASSWD}';
     client.id=chuck-java-producer
     key.serializer=org.apache.kafka.common.serialization.StringSerializer
     value.serializer=org.apache.kafka.common.serialization.StringSerializer
     topic=chuck-java-np-topic
