name: Point to North Cluster
on:
  workflow_dispatch:

env:
  KAFKA_PROXY_CONFIGMAP: '${{ secrets.NORTH_CM }}'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ogomezso-aks
        resource-group: ogomezso

    - uses: Azure/k8s-deploy@v1
      with:
        namespace: 'clients'
        manifests: '${{ env.KAFKA_PROXY_CONFIGMAP }}'
